

case $WEBSERVICE in
	AdesaSmartAuction)
		WS_SHORTNAME="asaws"
		CONNECTOR_PORT="9289"
		XMS="256"
		XMX="256"
		;;
	AttachmentWebService)
		WS_SHORTNAME="atws"
		CONNECTOR_PORT="9410"
		XMS="256"
		XMX="256"
		;;
	AuctionInfoWebService)
		WS_SHORTNAME="aiws"
		CONNECTOR_PORT="9405"
		XMS="256"
		XMX="256"
		;;
	AuctionInventoryRegistrationWebService)
		WS_SHORTNAME="airws"
		CONNECTOR_PORT="9309"
		XMS="256"
		XMX="256"
		;;
	AuthenticationWebService)
		WS_SHORTNAME="authws"
		CONNECTOR_PORT="9282"
		XMS="256"
		XMX="256"
		;;
	BlobServerWebService)
		WS_SHORTNAME="bsws"
		CONNECTOR_PORT="9384"
		XMS="64"
		XMX="256"
		;;
	CarProof)
		WS_SHORTNAME="carproof"
		CONNECTOR_PORT="9311"
		XMS="256"
		XMX="256"
		;;
	ChargesWebService)
		WS_SHORTNAME="chgws"
		CONNECTOR_PORT="9354"
		XMS="32"
		XMX="64"
		;;
	CreditWebService)
		WS_SHORTNAME="cws"
		CONNECTOR_PORT="9308"
		XMS="32"
		XMX="128"
		;;
No setenv.sh found for DentWizardMobileSynchronizationWebServices.
	DentWizardMobileSynchronizationWebServices)
		WS_SHORTNAME=""
		CONNECTOR_PORT="9291"
		XMS="256"
		XMX="256"
		;;
	ECRDataWebServices)
		WS_SHORTNAME="ecrdws"
		CONNECTOR_PORT="9001"
		XMS="64"
		XMX="1024"
		;;
	ECRDisplayWebService)
		WS_SHORTNAME="ecrdws"
		CONNECTOR_PORT="9313"
		XMS="64"
		XMX="256"
		;;
	ECRPriceWebServices)
		WS_SHORTNAME="ecrpws"
		CONNECTOR_PORT="9003"
		XMS="64"
		XMX="1024"
		;;
	ECRVehWebServices)
		WS_SHORTNAME="ecrvws"
		CONNECTOR_PORT="9007"
		XMS="64"
		XMX="1024"
		;;
	ECRWebService)
		WS_SHORTNAME="ecrws"
		CONNECTOR_PORT="9339"
		XMS="256"
		XMX="256"
		;;
	FeesWebService)
		WS_SHORTNAME="feesws"
		CONNECTOR_PORT="9324"
		XMS="32"
		XMX="32"
		;;
	InSightComplianceService)
		WS_SHORTNAME="ics"
		CONNECTOR_PORT="9460"
		XMS="256"
		XMX="256"
		;;
	InspectionSolutionsWebService)
		WS_SHORTNAME="insp"
		CONNECTOR_PORT="9461"
		XMS="256"
		XMX="256"
		;;
	InventorySearchWebService)
		WS_SHORTNAME="isws"
		CONNECTOR_PORT="9401"
		XMS="256"
		XMX="512"
		;;
	KioskWebService)
		WS_SHORTNAME="kws"
		CONNECTOR_PORT="9421"
		XMS="256"
		XMX="256"
		;;
	LaneserverJMXListener)
		WS_SHORTNAME="lsjl"
		CONNECTOR_PORT="80"
		XMS="256"
		XMX="256"
		;;
	MAFSWebservices)
		WS_SHORTNAME="mafs"
		CONNECTOR_PORT="9480"
		XMS="256"
		XMX="256"
		;;
	MMRTransactionsWebService)
		WS_SHORTNAME="mtws"
		CONNECTOR_PORT="9407"
		XMS="64"
		XMX="512"
		;;
	PriceBookCanadaWebService)
		WS_SHORTNAME="pbcws"
		CONNECTOR_PORT="9233"
		XMS="32"
		XMX="256"
		;;
	PriceBookWebService)
		WS_SHORTNAME="pbws"
		CONNECTOR_PORT="9283"
		XMS="32"
		XMX="256"
		;;
	PurchasedVehiclesWebService)
		WS_SHORTNAME="pvws"
		CONNECTOR_PORT="9295"
		XMS="256"
		XMX="256"
		;;
	RemoteListingNotificationWebService)
		WS_SHORTNAME="rlnws"
		CONNECTOR_PORT="9211"
		XMS="64"
		XMX="256"
		;;
	SalvageInfoWebService)
		WS_SHORTNAME="siws"
		CONNECTOR_PORT="9377"
		XMS="64"
		XMX="256"
		;;
	SpecialPricingWebService)
		WS_SHORTNAME="spws"
		CONNECTOR_PORT="9231"
		XMS="256"
		XMX="256"
		;;
	TRACrawler)
		WS_SHORTNAME=""
		CONNECTOR_PORT="19303"
		XMS="256"
		XMX="256"
		;;
	TransactionWebService)
		WS_SHORTNAME="tws"
		CONNECTOR_PORT="9212"
		XMS="256"
		XMX="256"
		;;
	UserChangeCrawlerWeb)
		WS_SHORTNAME=""
		CONNECTOR_PORT="9303"
		XMS="256"
		XMX="256"
		;;
	UserWebService)
		WS_SHORTNAME="uws"
		CONNECTOR_PORT="9296"
		XMS="64"
		XMX="256"
		;;
	VehicleDecoderWebService)
		WS_SHORTNAME="vdws"
		CONNECTOR_PORT="9073"
		XMS="32"
		XMX="512"
		;;
	VINDecoderBulkUpdateWebService)
		WS_SHORTNAME="vdbuws"
		CONNECTOR_PORT="9207"
		XMS="64"
		XMX="256"
		;;
No setenv.sh found for VinStyleIDtoMIDWebservice.
No server.xml found for VinStyleIDtoMIDWebservice.
	VinStyleIDtoMIDWebservice)
		WS_SHORTNAME=""
		CONNECTOR_PORT="9207"
		XMS="256"
		XMX="256"
		;;
esac
